`numpy.random.permutation` 함수를 이용하면 Series나 DataFrame의 로우를 쉽게 임의의 순서대로 재배치할 수 있다.<br/>
순서를 바꾸고 싶은 만큼의 길이를 `permutation` 함수에 넘기면 바뀐 순서가 담긴 정수 배열이 생성된다.

In [1]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [2]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [3]:
sampler = np.random.permutation(5)

In [4]:
sampler

array([0, 1, 4, 3, 2])

In [5]:
sampler = np.random.permutation(5)
sampler

array([1, 0, 2, 4, 3])

이 배열은 `ix` 기반의 색인이나 `take` 함수에서 사용할 수 있다.

In [7]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [8]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19
3  12  13  14  15

치환 없이 일부만 임의로 선택하려면 `permutation` 함수에서 반환된 배열에서 원하는 크기 k만큼만 처음부터 잘라내면 된다.<br/>
치환하지 않고 표본을 수집하는 효과적인 알고리즘도 많지만 이 방법은 손쉽게 사용할 수 있는 도구를 사용하는 간단한 방법이다.

In [11]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7

치환을 통해 표본을 생성하기 위한 가장 빠른 방법은 `np.random.randint`를 사용해서 생성한 난수를 이용하는 방법이다.

In [12]:
bag = np.array([5,7,-1,6,4])

In [15]:
sampler = np.random.randint(0,len(bag),size=10)

In [16]:
sampler

array([1, 4, 1, 1, 3, 4, 2, 3, 2, 3])

In [17]:
draws = bag.take(sampler)

In [18]:
draws

array([ 7,  4,  7,  7,  6,  4, -1,  6, -1,  6])