### Quiz

### loop 7,8,9

##### 7. 보어 구하기
- complement (보어)를 구하시오
- 50의 이진수는 110010
- 이진수 110010의 보어는 001101 (0을 1로바꾸고 1을 0으로 바꿈)
- 입력된 숫자의 보어를 10진수로 나타내시오

결과 예시
- 50 -> 13
- 100 -> 27

힌트
- 10진수를 2진수로 변환 : bin(n)
- 2진수를 10진수로 변환 : int(n,2)

xor - ^

In [143]:
# 문자열
number = 100

lis = list(bin(number).split('b')[1])

for i in range(len(lis)):
    if lis[i]=='1':
        lis[i]='2'
    if lis[i]=='0':
        lis[i]='1'
    if lis[i]=='2':
        lis[i]='0'

result = int("".join(lis),2)
result

27

In [193]:
# XOR 비트연산자 ^
number = 100
# TODO
result

27

##### 8. Bit Manipulation: Lonely Integer
- https://www.hackerrank.com/challenges/ctci-lonely-integer/problem
- 리스트에 하나만 있는 데이터 찾아내서 출력하기
- ls 리스트에 있는 데이터의 카운트를 세서 딕셔너리 형태로 바꿔줌
```
from collections import Counter 
d = dict(Counter(ls))
```
- [1,1,2,2,3] (입력) -> 3 (결과)
- [1,1,2,2] (입력) -> None (결과)

In [81]:
from collections import Counter

ls = [1,1,2,5,2,3,9,23]
d = dict(Counter(ls))
d

result = []

for key, value in d.items():
    if value == 1:
        result.append(key)

result.sort()
result

[3, 5, 9, 23]

##### 9. Recursion: Fibonacci Numbers
- https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem
- 피보나치 수열 초기값 a=0, b=1 에서 a는 b값이 되고 b는 a+b가 되는 a를 나열한 수열

In [102]:
# n 번째 피보나치 수열의 숫자
n = 10
a, b = 0, 1

for i in range(n):
    if i==0:
        result=0 
    else:
        a,b = b,a+b
    result=a

result 

34

In [35]:
# n 까지 피보나치 수열의 숫자들
def fib(num):
    a, b = 0, 1
    result=[]
    
    while a <num:
        if a>num:
            break
        result.append(a)
        a,b = b,a+b
            
    return result

fib(1000), fib(17)

([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987],
 [0, 1, 1, 2, 3, 5, 8, 13])

##### 10. 피보나치킨
- http://fibonachicken.herokuapp.com/

```
사람, 치킨, 피보나치수
 1    1     -
 2    1     -
 3    2     -
 4    3
 5    3     -
 6    4
 7    4
 8    5     -
 9    6
 10   6
 11   7
 12   8
 13   8     -
 14   9 
 15   9
 16   10
 17   11
 18   11
 19   12
 20   12
 21   13    -
```

In [9]:
def is_fib(num):
    if num in fib(num+1):
        return True
    else:
        return False

In [10]:
def prev_fib(num):
    return fib(num)[-1]

In [64]:
def fib_chicken(person):
    if is_fib(person)==False:
        
        
        
            
    if is_fib(person)==True:
        chicken = prev_fib(person)
    
    return chicken
               
fib_chicken(13)

8

In [36]:
is_fib(13), is_fib(17), is_fib(21)

(True, False, True)

In [37]:
prev_fib(13), prev_fib(17), prev_fib(21)

(8, 13, 13)

In [19]:
fib_chicken(42)

34

----

### numpy

In [1]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [3]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [12]:
np.r_[np.ones(7,dtype=int), np.array([5,5,5])]

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [13]:
np.array(range(10,21))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요

In [19]:
np.array(range(10,21))[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [24]:
na = np.arange(9).reshape(3,3); na

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [29]:
na[1:,1:]

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [41]:
na = np.random.randint(1,10,(3,4)); na

array([[7, 9, 8, 1],
       [8, 9, 4, 7],
       [8, 1, 4, 7]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [48]:
np.unique(na, return_counts=True)

(array([1, 4, 7, 8, 9]), array([2, 2, 3, 3, 2]))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [88]:
na = np.arange(1,13).reshape(3,4); na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
na = na.reshape(12,1)
np.random.shuffle(na)
na.reshape(3,4)

array([[ 1,  3,  8, 12],
       [11, 10,  7,  5],
       [ 6,  2,  9,  4]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [137]:
na = np.random.randint(1,11,(3,3)); na

array([[10,  6,  4],
       [ 6,  9, 10],
       [ 1,  4,  2]])

In [139]:
na = np.concatenate((na, np.sum(na, axis=0).reshape(1,3))); na

array([[10,  6,  4],
       [ 6,  9, 10],
       [ 1,  4,  2],
       [17, 19, 16]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [144]:
print('avg : ','%0.2f'%na.mean())

avg :  8.67


In [157]:
np.unique(na[na>na.mean()])

array([ 9, 10, 16, 17, 19])

In [158]:
na>na.mean()

array([[ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True,  True]], dtype=bool)

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [300]:
na = np.random.randint(1,21,(5,5)); na

array([[20, 19, 17, 19, 20],
       [10,  4, 15, 12,  8],
       [16, 16,  6, 12,  4],
       [10, 15, 12, 17, 16],
       [11,  6, 20,  1, 13]])

In [301]:
ls = na.reshape(1,25).tolist()
ls = [str(n) for n in ls[0]]

l=[]
for s in ls:
    if int(s)==na.max():
        s=(s+'(MAX)')
    elif int(s)==na.min():
        s=(s+'(MIN)')
    l.append(s)
    
np.asarray(l).reshape(5,5)

array([['20(MAX)', '19', '17', '19', '20(MAX)'],
       ['10', '4', '15', '12', '8'],
       ['16', '16', '6', '12', '4'],
       ['10', '15', '12', '17', '16'],
       ['11', '6', '20(MAX)', '1(MIN)', '13']],
      dtype='<U7')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [305]:
na = np.random.randint(100,131,(8,8)); na

array([[107, 115, 113, 107, 116, 119, 107, 126],
       [100, 128, 121, 123, 103, 109, 100, 118],
       [122, 100, 109, 103, 119, 127, 104, 127],
       [124, 103, 127, 114, 105, 120, 124, 100],
       [130, 121, 114, 109, 127, 119, 113, 105],
       [105, 103, 110, 119, 105, 105, 130, 119],
       [113, 107, 125, 129, 125, 128, 124, 104],
       [123, 115, 104, 129, 114, 117, 118, 128]])

In [307]:
ls = na.reshape(1,64).tolist()
ls = [str(n) for n in ls[0]]

l=[]
for s in ls:
    if int(s)%3==0 and int(s)%5==0:
        s='fbz'
    elif int(s)%3==0:
        s='fiz'
    elif int(s)%5==0:
        s='buz'
    l.append(s)
    
np.asarray(l).reshape(8,8)

array([['107', 'buz', '113', '107', '116', '119', '107', 'fiz'],
       ['buz', '128', '121', 'fiz', '103', '109', 'buz', '118'],
       ['122', 'buz', '109', '103', '119', '127', '104', '127'],
       ['124', '103', '127', 'fiz', 'fbz', 'fbz', '124', 'buz'],
       ['buz', '121', 'fiz', '109', '127', '119', '113', 'fbz'],
       ['fbz', '103', 'buz', '119', 'fbz', 'fbz', 'buz', '119'],
       ['113', '107', 'buz', 'fiz', 'buz', '128', '124', '104'],
       ['fiz', 'buz', '104', 'fiz', 'fiz', 'fiz', '118', '128']],
      dtype='<U3')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [364]:
# num = int(input("number : "))
# tmp,ls=[],[]


# for i in range(1,num+1):
#     for j in range(1,num+1):
#         tmp.append(i*j)
      
# ls.append(tmp)
# np.asarray(ls).reshape(5,5)

In [365]:
num = int(input("number : "))
ls=[(np.array([n for n in range(1,num+1)])*i).tolist() for i in range(1,num+1)]

np.asarray(ls)

number : 7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])