In [31]:
########### numpy 2강 - array 인덱싱 이해하기

In [32]:
arr = np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[5]

5

In [35]:
arr[5:8]

array([5, 6, 7])

In [36]:
arr[5:8]=12

In [37]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [38]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [39]:
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

In [40]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [42]:
arr2d[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr2d[3]

array([13, 14, 15, 16])

In [44]:
arr2d[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [46]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [47]:
arr2d[3,2]

15

In [48]:
arr2d[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [49]:
arr2d[:2, 1:3] = 0

In [50]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
names = np.array(["aaaaaa","bbbbbb","aaaaaa","dddddd","eeeeee"])
data = np.random.randn(5,4)

In [52]:
names

array(['aaaaaa', 'bbbbbb', 'aaaaaa', 'dddddd', 'eeeeee'],
      dtype='<U6')

In [53]:
data

array([[-0.3618941 , -0.19497656,  2.80154498, -1.01190632],
       [ 0.2072055 ,  0.42204132, -0.75910033,  0.94804199],
       [ 1.12706136,  1.13718477, -2.70421138, -0.10922946],
       [ 0.63790881,  0.76258772,  0.59036755, -0.3096336 ],
       [ 0.99367913,  0.19918746,  0.01430668,  0.72740397]])

In [54]:
names =="aaaaaa"

array([ True, False,  True, False, False], dtype=bool)

In [55]:
data[names == "aaaaaa", :]

array([[-0.3618941 , -0.19497656,  2.80154498, -1.01190632],
       [ 1.12706136,  1.13718477, -2.70421138, -0.10922946]])

In [56]:
data[names == "eeeeee", :]

array([[ 0.99367913,  0.19918746,  0.01430668,  0.72740397]])

In [57]:
data[(names=="aaaaaa") | (names=="eeeeee"), :]

array([[-0.3618941 , -0.19497656,  2.80154498, -1.01190632],
       [ 1.12706136,  1.13718477, -2.70421138, -0.10922946],
       [ 0.99367913,  0.19918746,  0.01430668,  0.72740397]])

In [58]:
data[:,3]

array([-1.01190632,  0.94804199, -0.10922946, -0.3096336 ,  0.72740397])

In [59]:
data[:,3] < 0

array([ True, False,  True,  True, False], dtype=bool)

In [60]:
data[ data[:,3]<0, : ]

array([[-0.3618941 , -0.19497656,  2.80154498, -1.01190632],
       [ 1.12706136,  1.13718477, -2.70421138, -0.10922946],
       [ 0.63790881,  0.76258772,  0.59036755, -0.3096336 ]])

In [61]:
data[ data[:,3]<0, : ] = 0

In [62]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.2072055 ,  0.42204132, -0.75910033,  0.94804199],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.99367913,  0.19918746,  0.01430668,  0.72740397]])