In [15]:
############# 데이터 처리하기 3강 - DataFrame 데이터 변형하기

In [52]:
import numpy as np
import pandas as pd

In [53]:
df = pd.DataFrame({"k1":['one']*3 + ['two']*4,
                   "k2":list("1123344")})

In [54]:
df

k1 k2
0  one  1
1  one  1
2  one  2
3  two  3
4  two  3
5  two  4
6  two  4

In [55]:
df.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [56]:
df.drop_duplicates()

k1 k2
0  one  1
2  one  2
3  two  3
5  two  4

In [57]:
df["v1"]= np.arange(7)

In [58]:
df

k1 k2  v1
0  one  1   0
1  one  1   1
2  one  2   2
3  two  3   3
4  two  3   4
5  two  4   5
6  two  4   6

In [59]:
df.drop_duplicates(["k1"])

k1 k2  v1
0  one  1   0
3  two  3   3

In [60]:
df.drop_duplicates(["k1","k2"])

k1 k2  v1
0  one  1   0
2  one  2   2
3  two  3   3
5  two  4   5

In [61]:
df.drop_duplicates(["k1","k2"], keep='last')

k1 k2  v1
1  one  1   1
2  one  2   2
4  two  3   4
6  two  4   6

In [62]:
df.drop_duplicates(["k1","k2"], keep='first')

k1 k2  v1
0  one  1   0
2  one  2   2
3  two  3   3
5  two  4   5

In [63]:
df2 = pd.DataFrame({'food':['bacon', 'pulled pork', 'bacon', 'Pastrami',
                           'corned beef','Bacon','pastrami','honey ham',
                           'nova lox'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [64]:
df2

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [65]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [66]:
meat_to_animal

{'bacon': 'pig',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastrami': 'cow',
 'pulled pork': 'pig'}

In [67]:
meat_to_animal['bacon']

'pig'

In [68]:
df2['animal'] = df2['food'].apply(lambda x:meat_to_animal[x.lower()])

In [69]:
df2

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [70]:
s = pd.Series([1., -999., 2., -999., -1000., 3.])

In [71]:
s

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [72]:
s2 = s.replace(-999, np.nan)

In [73]:
s2

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [74]:
s2.replace(np.nan, 0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

In [75]:
s2.fillna(0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

### Categories 자료형

In [76]:
df3 = pd.DataFrame({"id":[1,2,3,4,5,6], "raw_grade":list("abbaae")})

In [77]:
df3

id raw_grade
0   1         a
1   2         b
2   3         b
3   4         a
4   5         a
5   6         e

In [78]:
df3['grade'] = df3['raw_grade'].astype("category")

In [79]:
df3

id raw_grade grade
0   1         a     a
1   2         b     b
2   3         b     b
3   4         a     a
4   5         a     a
5   6         e     e

In [80]:
df3['grade']

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): [a, b, e]

In [81]:
df3['grade'].cat.categories

Index(['a', 'b', 'e'], dtype='object')

In [82]:
df3['grade'].cat.categories=["very good","good","very bad"]

In [83]:
df3

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [84]:
df3['grade']= df3['grade'].cat.set_categories(["very bad","bad","medium","good","very good"])

In [85]:
df3

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [86]:
df3['grade']

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, object): [very bad, bad, medium, good, very good]

In [87]:
df3

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [88]:
df3.sort_values(by="grade")

id raw_grade      grade
5   6         e   very bad
1   2         b       good
2   3         b       good
0   1         a  very good
3   4         a  very good
4   5         a  very good

In [89]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]

In [90]:
cats = pd.cut(ages, bins)

In [91]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [92]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [93]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [94]:
cats.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [95]:
group_names=["youth","youngAdult","middleAged","Senior"]

In [96]:
pd.cut(ages, bins, labels=group_names)

[youth, youth, youth, youngAdult, youth, ..., youngAdult, Senior, middleAged, middleAged, youngAdult]
Length: 12
Categories (4, object): [youth < youngAdult < middleAged < Senior]

In [97]:
data = np.random.rand(20)

In [98]:
data

array([ 0.42922535,  0.75090856,  0.26173514,  0.91739214,  0.00155979,
        0.44796064,  0.30588755,  0.03144897,  0.46218183,  0.47180955,
        0.8839111 ,  0.74201586,  0.1406569 ,  0.09380708,  0.13782117,
        0.01573551,  0.96170465,  0.42408817,  0.48839993,  0.38493487])

In [99]:
pd.cut(data, 4, precision=2)

[(0.24, 0.48], (0.72, 0.96], (0.24, 0.48], (0.72, 0.96], (0.0006, 0.24], ..., (0.0006, 0.24], (0.72, 0.96], (0.24, 0.48], (0.48, 0.72], (0.24, 0.48]]
Length: 20
Categories (4, interval[float64]): [(0.0006, 0.24] < (0.24, 0.48] < (0.48, 0.72] < (0.72, 0.96]]

In [100]:
data2 = np.random.randn(1000)

In [101]:
data2[:5]

array([-0.23055311,  0.69691826,  0.07453839, -0.74471082, -0.24042598])

In [102]:
cats = pd.qcut(data2, 4) # qcut은 4분위로 categorize

In [103]:
cats

[(-0.686, 0.00628], (0.638, 3.451], (0.00628, 0.638], (-3.493, -0.686], (-0.686, 0.00628], ..., (-3.493, -0.686], (0.638, 3.451], (-3.493, -0.686], (-0.686, 0.00628], (0.638, 3.451]]
Length: 1000
Categories (4, interval[float64]): [(-3.493, -0.686] < (-0.686, 0.00628] < (0.00628, 0.638] < (0.638, 3.451]]