In [7]:
########### numpy 1강 - numpy ndarray 이해하기

In [8]:
import numpy as np

In [9]:
data1 = [6,7,8,9.5,10]

In [10]:
arr1 = np.array(data1)

In [11]:
arr1.shape

(5,)

In [12]:
data2 = [[1,2,3,4],
        [5,6,7,8]]

In [13]:
arr2 = np.array(data2)

In [14]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.shape

(2, 4)

In [16]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [21]:
arr = np.array([1,2,3,4,5], dtype=np.float64)

In [22]:
arr.dtype

dtype('float64')

In [23]:
float_arr = arr.astype(np.float64)

In [24]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [25]:
float_arr.dtype

dtype('float64')

In [26]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [27]:
arr2 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [28]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [29]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [30]:
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])