In [63]:
############ numpy 3강 - array 관련 함수 사용하기

In [64]:
arr = np.arange(1,10)

In [65]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [67]:
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

In [68]:
x = np.random.randn(8); x

array([-0.49513777, -0.00974768, -0.34925678,  2.35226758, -0.6021094 ,
       -1.13164788, -0.89039095,  1.11124371])

In [69]:
y = np.random.randn(8); y

array([ 0.1482796 , -0.95677258,  0.08026259, -1.05161936, -0.10149999,
       -0.34748908,  0.08883105,  0.57385467])

In [70]:
np.maximum(x,y)

array([ 0.1482796 , -0.00974768,  0.08026259,  2.35226758, -0.10149999,
       -0.34748908,  0.08883105,  1.11124371])

In [71]:
arr = np.random.randn(5,4)

In [72]:
arr

array([[ 0.76728498,  0.72581281,  0.49724715,  0.1181784 ],
       [-0.04549349, -0.31149828, -0.18253263,  0.50185971],
       [-2.00822634,  2.21617311,  2.3377847 , -0.96019258],
       [ 0.26824521, -0.88174739,  0.43946827,  1.56461919],
       [ 1.04791532, -0.94108895,  1.08779635, -1.29501848]])

In [73]:
arr.sum()

4.9465870530795932

In [74]:
arr.mean()

0.24732935265397965

In [75]:
arr.sum(axis=0)

array([ 0.02972569,  0.80765129,  4.17976383, -0.07055376])

In [76]:
arr.sum(axis=1)

array([ 2.10852334, -0.0376647 ,  1.58553889,  1.39058528, -0.10039576])

In [77]:
arr>0

array([[ True,  True,  True,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True, False]], dtype=bool)

In [78]:
(arr>0).sum()

12

In [79]:
arr = np.random.randn(8)

In [80]:
arr

array([ 0.22281287,  0.61649291,  1.72725094, -0.31314536, -0.29246116,
        0.4225626 ,  1.12166323,  0.26558114])

In [81]:
np.sort(arr) #오름차순 정렬

array([-0.31314536, -0.29246116,  0.22281287,  0.26558114,  0.4225626 ,
        0.61649291,  1.12166323,  1.72725094])

In [82]:
np.sort(arr)[::-1] #내림차순 정렬

array([ 1.72725094,  1.12166323,  0.61649291,  0.4225626 ,  0.26558114,
        0.22281287, -0.29246116, -0.31314536])

In [83]:
arr = np.random.randn(5,3)

In [84]:
arr

array([[ 0.04979102,  0.23699963, -1.19173095],
       [-1.17997106,  0.20004972, -2.07502017],
       [-0.24428666, -0.24713348,  0.92377956],
       [ 0.08579181, -1.70500426,  2.24868202],
       [ 0.57070633, -1.44978836, -0.15183775]])

In [85]:
np.sort(arr)

array([[-1.19173095,  0.04979102,  0.23699963],
       [-2.07502017, -1.17997106,  0.20004972],
       [-0.24713348, -0.24428666,  0.92377956],
       [-1.70500426,  0.08579181,  2.24868202],
       [-1.44978836, -0.15183775,  0.57070633]])

In [86]:
np.sort(arr, axis=1) # 행정렬

array([[-1.19173095,  0.04979102,  0.23699963],
       [-2.07502017, -1.17997106,  0.20004972],
       [-0.24713348, -0.24428666,  0.92377956],
       [-1.70500426,  0.08579181,  2.24868202],
       [-1.44978836, -0.15183775,  0.57070633]])

In [87]:
np.sort(arr, axis=0) #열정렬

array([[-1.17997106, -1.70500426, -2.07502017],
       [-0.24428666, -1.44978836, -1.19173095],
       [ 0.04979102, -0.24713348, -0.15183775],
       [ 0.08579181,  0.20004972,  0.92377956],
       [ 0.57070633,  0.23699963,  2.24868202]])

In [88]:
large_arr=np.random.randn(150); large_arr

array([ 0.56611499, -0.60009479,  1.37439633,  0.8529789 , -0.00431158,
        1.32367969, -1.08932033,  0.34985878, -0.26847342,  0.03128303,
        0.52185358,  0.63097852, -2.65129575,  0.64163529,  0.615153  ,
       -0.8890901 , -0.60429609,  0.52762478, -0.55913676, -0.92168014,
       -0.64726787, -0.96458292,  0.01055827,  0.57129975, -0.03995839,
        0.73612237,  0.3101235 , -0.21867366, -1.37988216,  0.0810045 ,
       -0.45021414, -0.37211355, -0.30726486,  0.04842193,  0.03600344,
        0.67897334,  1.45625814,  0.66592672, -0.66211553,  0.61871967,
        0.57469321, -0.97247968, -0.99509425,  0.67375044,  1.46497121,
       -0.72995524, -0.08420033,  0.86682278,  0.97832853,  1.05176245,
       -0.32411666,  1.74566549,  0.94294487,  0.10719244,  0.42647902,
        0.71582865, -0.1896454 , -0.45054613, -1.71177583,  0.16068891,
        0.78301229,  1.50287728,  0.72588009, -0.32366677, -0.08037298,
       -0.73627459, -1.10494056, -1.54109689,  0.60452785,  0.53

In [89]:
np.sort(large_arr)[::-1]

array([ 2.69476009,  1.83039148,  1.75708353,  1.74566549,  1.64372615,
        1.57028005,  1.50287728,  1.46497121,  1.45625814,  1.37439633,
        1.32367969,  1.30102527,  1.30096876,  1.10313448,  1.05176245,
        1.04302659,  0.97832853,  0.96468734,  0.94294487,  0.94051029,
        0.87924595,  0.86682278,  0.8529789 ,  0.84380867,  0.81039482,
        0.78301229,  0.7627847 ,  0.76184558,  0.73612237,  0.72588009,
        0.71582865,  0.67897334,  0.67375044,  0.66592672,  0.64556414,
        0.64163529,  0.63097852,  0.61871967,  0.615153  ,  0.60452785,
        0.57469321,  0.57129975,  0.56611499,  0.54171567,  0.53985377,
        0.53465075,  0.52762478,  0.52185358,  0.47060924,  0.45888164,
        0.43088831,  0.42647902,  0.4007518 ,  0.38419274,  0.34985878,
        0.3101235 ,  0.28310725,  0.27860077,  0.25074934,  0.24105476,
        0.18610914,  0.17000332,  0.16068891,  0.11205754,  0.10719244,
        0.10694392,  0.10511305,  0.0810045 ,  0.075037  ,  0.06

In [90]:
np.sort(large_arr)[::-1][int(0.05*len(large_arr))]

1.4649712105379744

In [91]:
names = np.array(["charles","kilho","hayoung","charles","hayoung","kilho","kilho"])
ints=np.array([3,3,3,2,2,1,1,4,4,])

In [92]:
np.unique(names)

array(['charles', 'hayoung', 'kilho'],
      dtype='<U7')

In [93]:
np.unique(ints)

array([1, 2, 3, 4])