##### Numpy - Make

In [4]:
# ndarray 
# ndim: 행렬의 차원, shape: 행렬의 모양

# 1차원 행렬
array = np.array([1,2,3])
array = np.array(range(5))
print(type(array))
print(array)

<class 'numpy.ndarray'>
[0 1 2 3 4]


In [6]:
# 2차원 행렬
array = np.array(
    [[1,2,3],
    [4,5,6]],
)
print(array)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3차원 행렬
array = np.array(
    [[[1,2,3],
    [4,5,6]],
    [[1,2,3],
    [4,5,6]]],

)
print(array)
print(array.ndim, array.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3 (2, 2, 3)


In [9]:
# reshape - 행렬의 모양을 바꿀때 사용합니다.
na = np.array(range(10))
na

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
na.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
np.reshape(na, (5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
# index 
# 행렬 데이터를 수정하거나, 가져오거나, 자를때 사용됩니다.

In [17]:
array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [20]:
array[1][0][1]

2

In [21]:
array[1, 0, 1]

2

In [22]:
array[1:, :, 1:]

array([[[2, 3],
        [5, 6]]])

In [23]:
# 데이터 수정
ls = np.array(range(5))
ls

array([0, 1, 2, 3, 4])

In [24]:
ls[2] = 0
ls

array([0, 1, 0, 3, 4])

In [25]:
ls[3:] = 0
ls

array([0, 1, 0, 0, 0])

In [36]:
# zeros - 행렬을 만들고 0을 채웁니다.
z = np.zeros((2, 3, 2), dtype=int)
z, z.ndim, z.shape

(array([[[0, 0],
         [0, 0],
         [0, 0]],
 
        [[0, 0],
         [0, 0],
         [0, 0]]]), 3, (2, 3, 2))

In [49]:
# ones - 행렬을 만들고 1을 채웁니다.
one = np.ones((4,3), dtype=int)
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
# eye - 단위행렬 데이터
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# like - 행렬안에 있는 모든 숫자를 0 또는 1로 변경할수 있습니다.

In [46]:
np.ones_like(z)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [50]:
np.zeros_like(one)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
# empty - 빈행렬, 안에 어떤값이 들어갈지 몰라요.

In [53]:
np.empty((5,3))

array([[-2.68156159e+154, -2.68677968e+154,  3.95252517e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [54]:
# arange 
# range 사용방법이 같습니다.
# 하지만 range보다 속도가 빠릅니다.

In [55]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [57]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [60]:
# 속도비교
size = 10**6
size = int(1E6)
size

1000000

In [65]:
%time for x in range(size): x**2
%time for x in np.arange(size): x**2    

CPU times: user 339 ms, sys: 1.85 ms, total: 341 ms
Wall time: 340 ms
CPU times: user 211 ms, sys: 215 µs, total: 211 ms
Wall time: 211 ms


In [66]:
# linspace, logspace

In [68]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [70]:
# log10(x1)=2, log10(x2)=3, log10(x3)=4
# x1:100, x2:1000, x3:10000
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [73]:
# 2, 2.5, 3
# log10(x1)=2, log10(x2)=2.5, log10(x3)=3
np.logspace(2,3,3)

array([ 100.        ,  316.22776602, 1000.        ])

In [74]:
10**2, 10**2.5, 10**3

(100, 316.22776601683796, 1000)

##### random
- seed : 랜덤변수의 설정값
- rand : 균등분포(uniform)로 난수를 발생시킵니다.
- randn : 정규분포(gaussian)로 난수를 발생시킵니다.
- randint : 정수로 난수를 발생시킵니다.(균등분포)
- suffle : 행렬 데이터를 섞어 줍니다.
- choice : 특정 범위의 숫자를 선택해 줍니다.(확률 설정이 가능)

In [93]:
np.random.seed(1)
rd = np.random.rand(10)
rd

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [94]:
rdn = np.random.randn(10)
rdn

array([ 1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,  1.46210794,
       -2.06014071, -0.3224172 , -0.38405435,  1.13376944, -1.09989127])

In [161]:
# randint
r = np.random.randint(5, 10, (2,3))
r

array([[5, 9, 7],
       [5, 7, 9]])

In [188]:
r = np.random.randint(5, size=(4,3))
r

array([[3, 2, 3],
       [4, 4, 3],
       [0, 0, 0],
       [4, 1, 4]])

In [186]:
# shuffle - 데이터의 순서를 변경할수 있습니다.

In [191]:
np.random.shuffle(r)
r

array([[4, 4, 3],
       [0, 0, 0],
       [4, 1, 4],
       [3, 2, 3]])

In [207]:
# choice
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])

array([4, 3, 4, 4, 4, 4, 0, 3, 4, 3])

In [194]:
r

array([[4, 4, 3],
       [0, 0, 0],
       [4, 1, 4],
       [3, 2, 3]])

In [208]:
# unique : 행열 데이터에서 유일값과 유일값의 갯수를 확인할수 있습니다.
number, counts = np.unique(r, return_counts=True)
print(number)
print(counts)

[0 1 2 3 4]
[3 1 1 3 4]


In [209]:
# stack

In [210]:
na1 = np.arange(5)
na2 = np.arange(5,10)
print(na1)
print(na2)

[0 1 2 3 4]
[5 6 7 8 9]


In [213]:
na3 = np.stack((na1, na2), axis=0)
print(na3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [215]:
na3 = np.stack((na1, na2), axis=1)
print(na3)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [218]:
na1 = np.arange(1,7).reshape(2,3)
na2 = np.arange(7,13).reshape(2,3)
print(na1)
print(na2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [219]:
na4 = np.stack((na1, na2), axis=0)
print(na4)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [220]:
na5 = np.stack((na1, na2), axis=1)
print(na5)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [221]:
na6 = np.stack((na1, na2), axis=2)
print(na6)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [222]:
# concatenate 결합

In [227]:
na1 = np.random.randint(10, size=(2,3))
na1

array([[7, 5, 9],
       [1, 3, 9]])

In [228]:
na2 = np.random.randint(10, size=(3,2))
na2

array([[3, 3],
       [3, 6],
       [1, 3]])

In [229]:
na3 = np.random.randint(10, size=(3,3))
na3

array([[0, 5, 0],
       [5, 2, 7],
       [6, 4, 0]])

In [230]:
# 세로 결합 - 컬럼 갯수가 맞아야 합니다.
np.concatenate((na1, na3))

array([[7, 5, 9],
       [1, 3, 9],
       [0, 5, 0],
       [5, 2, 7],
       [6, 4, 0]])

In [231]:
# 가로 결합 - 로우갯수가 맞아야 합니다.
np.concatenate((na2, na3), axis=1)

array([[3, 3, 0, 5, 0],
       [3, 6, 5, 2, 7],
       [1, 3, 6, 4, 0]])

In [232]:
# split

In [233]:
r = np.arange(0,10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
np.split(r, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [235]:
np.split(r, [2,4,6,8])

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [236]:
r = np.random.randint(10, size=(4,6))
r

array([[2, 4, 8, 7, 6, 7],
       [7, 1, 7, 7, 3, 8],
       [3, 0, 6, 3, 0, 6],
       [5, 9, 6, 4, 6, 6]])

In [237]:
# vsplit, hsplit

In [245]:
# vsplit : 수평을 자릅니다.
np.vsplit(r, 2)

[array([[2, 4, 8, 7, 6, 7],
        [7, 1, 7, 7, 3, 8]]), array([[3, 0, 6, 3, 0, 6],
        [5, 9, 6, 4, 6, 6]])]

In [ ]:
# hsplit : 수직을 자릅니다.

In [251]:
# list 타입이 아니면 등분을 합니다.
np.hsplit(r, 3)

[array([[2, 4],
        [7, 1],
        [3, 0],
        [5, 9]]), array([[8, 7],
        [7, 7],
        [6, 3],
        [6, 4]]), array([[6, 7],
        [3, 8],
        [0, 6],
        [6, 6]])]

In [252]:
n1, n2 = np.hsplit(r, 2)
print(n1)
print(n2)

[[2 4 8]
 [7 1 7]
 [3 0 6]
 [5 9 6]]
[[7 6 7]
 [7 3 8]
 [3 0 6]
 [4 6 6]]


In [244]:
# sort

In [253]:
r1 = np.random.randint(10, size=(3,3))
r1

array([[2, 2, 4],
       [1, 2, 3],
       [9, 3, 6]])

In [254]:
# 가로 소팅
r1.sort()
r1

array([[2, 2, 4],
       [1, 2, 3],
       [3, 6, 9]])

In [255]:
# 세로 소팅
r1.sort(axis=0)
r1

array([[1, 2, 3],
       [2, 2, 4],
       [3, 6, 9]])

In [257]:
# 컬럼으로 결합
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [258]:
# 로우로 결합
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])