##### 기본 연산

In [2]:
ls = [1,2,3]
ls*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
na = np.array([1,2,3])
na*3

array([3, 6, 9])

In [8]:
na2 = np.array([4,5,6])
na, na2

(array([1, 2, 3]), array([4, 5, 6]))

In [9]:
# 행렬연산
na + na2

array([5, 7, 9])

In [14]:
# 비교연산
na == 2, na2 > 4

(array([False,  True, False]), array([False,  True,  True]))

In [16]:
# 필터링
na[na == 2], na2[na2 > 4]

(array([2]), array([5, 6]))

In [18]:
# 3의 배수만 출력
na3 = np.arange(10)
na3[na3 % 3 == 0]

array([0, 3, 6, 9])

In [20]:
ls1 = np.array([1,2,3,4,5])
ls2 = np.array([1,0,3,0,5])
ls1[ls1 == ls2]

array([1, 3, 5])

In [21]:
# 브로드캐스팅

In [23]:
na = np.array(range(12)).reshape(3,4)
na

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
na + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
na1 = np.array(range(4))
na1

array([0, 1, 2, 3])

In [26]:
na + na1

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [29]:
na2 = np.array(range(3))[:, np.newaxis]
na2

array([[0],
       [1],
       [2]])

In [30]:
na

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
na + na2

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [32]:
# functions
# min, max, argmin, argmax

In [36]:
na = np.random.randint(10, size=(2,3))
na

array([[4, 8, 9],
       [3, 1, 3]])

In [39]:
# argmin,argmax - 최소값, 최대값의 위치 index를 출력합니다.
na.min(), na.max(), na.argmin(), na.argmax()

(1, 9, 4, 2)

In [40]:
# sum, mean, median, std, var

In [46]:
np.sum(na)

28

In [42]:
np.sum(na, axis=0) # 컬럼끼리 더해짐

array([ 7,  9, 12])

In [43]:
np.sum(na, axis=1) # 로우끼리 더해짐

array([21,  7])

In [48]:
np.mean(na), np.median(na)

(4.666666666666667, 3.5)

In [ ]:
# all, any

In [49]:
na = np.array([1,2,3])
na

array([1, 2, 3])

In [50]:
na2 = na
na2

array([1, 2, 3])

In [51]:
na3 = np.array([1,0,3])
na3

array([1, 0, 3])

In [52]:
na, na2, na3

(array([1, 2, 3]), array([1, 2, 3]), array([1, 0, 3]))

In [54]:
na == na2, na == na3

(array([ True,  True,  True]), array([ True, False,  True]))

In [ ]:
# all - 하나라도 false이면 false 입니다. and 유사

In [56]:
np.all(na == na2), np.all(na == na3)

(True, False)

In [ ]:
# any - 하나라도 ture이면 true 입니다. or 유사

In [57]:
np.any(na == na2), np.any(na == na3)

(True, True)

In [61]:
# 사분위수
na = np.arange(100,201)
na

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200])

In [62]:
np.percentile(na, 25)

125.0

In [63]:
# 지수함수, 로그함수
na = np.arange(1,6)
na

array([1, 2, 3, 4, 5])

In [64]:
np.exp(na)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [65]:
np.log(na)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [66]:
# 퍼포먼스 비교

In [68]:
# 10**7 개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간

In [69]:
ls = []
size = int(1E7)

In [70]:
ls = [num for num in range(size)]
len(ls)

10000000

In [72]:
na = np.arange(size)
len(na)

10000000

In [73]:
%%time
count = 0
for idx in ls:
    if (ls[idx] % 3 == 0) or (ls[idx] % 5 == 0):
        count += 1
count

CPU times: user 2.06 s, sys: 34.4 ms, total: 2.09 s
Wall time: 2.1 s


In [74]:
%%time
count = len(na[(na % 3 == 0) | (na % 5 == 0)])
count

CPU times: user 237 ms, sys: 35.8 ms, total: 272 ms
Wall time: 271 ms
